language: none

build:
    pre_ci:
        - env
        - apt-get install -y dos2unix
        - image=${REPO_NAME#*-}
        - echo $image
        - docker build --no-cache -t justin8/$image .
        - version=$(docker run justin8/$image cat /version | dos2unix)
        - echo $version
        - docker tag -f justin8/$image:latest justin8/$image:$version
        - docker images
    push:
        - image=${REPO_NAME#*-}
        - version=$(docker run justin8/$image cat /version | dos2unix)
        - echo "Pushing justin8/$image:$version"
        - docker push justin8/$image:$version
        - docker push justin8/$image:latest

integrations:
    hub:
        - integrationName: dockerhub
          type: docker
